/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

declare const self: ServiceWorkerGlobalScope;

// Take control of all pages immediately
clientsClaim();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Offline fallback for navigation requests
const FALLBACK_HTML_URL = '/offline.html';

// Cache the offline page during installation
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('offline-cache').then((cache) => {
      return cache.add(FALLBACK_HTML_URL);
    })
  );
});

// Handle navigation requests with offline fallback
registerRoute(
  new NavigationRoute(
    async ({ request }) => {
      try {
        // Try to fetch from network
        const response = await fetch(request);
        return response;
      } catch (error) {
        // If network fails, try cache
        const cache = await caches.match(request);
        if (cache) {
          return cache;
        }
        
        // If cache fails, return offline page
        const offlineCache = await caches.match(FALLBACK_HTML_URL);
        if (offlineCache) {
          return offlineCache;
        }
        
        // Last resort: return a basic offline response
        return new Response(
          '<html><body><h1>Sin conexión</h1><p>No hay conexión a Internet</p></body></html>',
          {
            headers: { 'Content-Type': 'text/html' },
          }
        );
      }
    }
  )
);

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
